# Site settings
title: Howpage
email: johannesborchard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "www.howpage.de" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
