# Site settings
title: Howpage
email: 
description: Jeder kann Webseiten erstellen
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.howpage.de" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
